version: '3.8'

services:
  name-server:
    image: name-server
    container_name: name-server
    build:
      context: ./name-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    networks:
      - microservices-network

  scaa:
    image: scaa
    container_name: scaa
    build:
      context: ./scaa
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:scaa-db
      - SPRING_DATASOURCE_DRIVERCLASSNAME=org.h2.Driver
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_H2_CONSOLE_ENABLED=true
      - SPRING_H2_CONSOLE_PATH=/h2
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true
    depends_on:
      - name-server
      - rabbitmq
    networks:
      - microservices-network

  ass-cache:
    image: ass-cache
    container_name: ass-cache
    build:
      context: ./ass-cache
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka/
    depends_on:
      - name-server
      - scaa
      - rabbitmq
    networks:
      - microservices-network

  api-gateway:
    image: api-gateway
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8765:8765"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://name-server:8761/eureka/
    depends_on:
      - name-server
      - scaa
      - ass-cache
    networks:
      - microservices-network

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge